displayName=Previous Prayer Tracker
author=MustacheAltun
description=Tracks and displays recent or previous overhead prayers
tags=prayer,overhead,pvm,pvp
plugins=com.previousprayer.PreviousPrayerPlugin